config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end
 resources :cart_items

 resources :orders do
   member do
     post :pay_with_alipay
     post :pay_with_wechat
     post :apply_to_cancel
   end
 end

 namespace :account do
   resources :orders
 end

root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title,presence: true
  validates :price, presence: {message:"请填入商品价格"}
  validates :quantity, presence: {message:"请填入商品数量"}
  mount_uploader :image, ImageUploader
  mount_uploaders :avatars, AvatarUploader
  serialize :avatars, JSON

  has_many :cart_items

  belongs_to :category

  has_many :groupships
has_many :groups, :through => :groupships
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout 'admin'

  def index
   @products = Product.all
  end

  def new
    @product = Product.new

  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def show
    @product  = Product.find(params[:id])



  end

  def edit
    @product  = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path

  end

  private

  

    def product_params
      params.require(:product).permit(:title,:description,:quantity,:price,:image,{avatars: []},:category_id,{group_ids: []},:publish_on)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
    current_cart.add_product_to_cart(@product)

    flash[:notice]= "成功#{@product.title}加入购物车"
  else
    flash[:warning]= "购物车中已有该物品"
  end
    redirect_to :back
  end

  def index
   @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    set_page_title @product.title

    page_description = view_context.truncate(@product.description, :length =>5)
    set_page_description "#{page_description}"

    set_page_keywords    "你好啊#{@product.price}"

    set_page_image @product.image_url

  end


end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin,@product] do |f| %>
<div class="group">
  <%= f.input :title,label:"名称" %>
</div>

<div class="group">
  <%= f.input :description,label:"描述" %>
</div>

<div class="group">
  <%= f.input :quantity,label:"数量" %>
</div>

<div class="group">
  <%= f.input :price,label:"价格" %>
</div>

<div class="group">
  <%= f.input :image, as: :file %>
</div>

<div class="group">
  <!-- <%#= f.input :avatars, as: :file, multiple: true %> -->
  <!-- <%#= form.file_field :avatars, multiple: true %> -->
  <%= f.input :avatars, multiple: true %>
</div>

<%= f.submit "确定",data: {disable_with: "提交中..."},class:"btn btn-sm btn-primary" %>
<% end %>

app/views/admin/products/edit.html.erb
<h2>Edit Product</h2>
<%= simple_form_for [:admin,@product] do |f| %>
<div class="group">
  <%= f.input :title,label:"名称" %>
</div>

<div class="group">
 <%= f.input :publish_on, :as => :string %>

</div>

<div class="group">
   <%= f.association :category,label:"种类" %>
  <!-- <%#= f.select :category_id, Category.all.map{|x| [x.name, x.id]},{}, :class => "form-control" %> -->
</div>

<div class="group">
  <%= f.association :groups %>
</div>

<div class="group">
  <%= f.input :description,label:"描述" %>
</div>

<div class="group">
  <%= f.input :quantity,label:"数量" %>
</div>

<div class="group">
  <%= f.input :price,label:"价格" %>
</div>

 <% if !@product.image.file.nil? %>
 <span>目前商品图</span>
 <br>
 <%= image_tag(@product.image.thumb.url) %>
 <% else %>
 <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
 <% end %>

 <% if @product.avatars.present? %>
 <span>目前展示图</span>
 <% @product.avatars.each do |a| %>
 展示图: <%= image_tag(a.thumb.url) %>
 <% end %>
 <% end %>
<div class="group">
  <%= f.input :image, as: :file %>
</div>

<div class="group">
  <%= f.file_field :avatars ,multiple: 'true' %>
</div>

<%= f.submit "确定",data: {disable_with: "提交中..."},class:"btn btn-sm btn-primary" %>
<% end %>

<script>

  $("#product_category_id").select2();
  $("#product_group_ids").select2();
  // $(".form-control.date.optional").datepicker();
  $("#product_publish_on").datepicker({ format: "yyyy/mm/dd" });
  autosize($("#product_description"));
</script>

app/views/admin/products/index.html.erb
<h2> Product List </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th width="100"> Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.image.present? %>
              <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= link_to("Edit", edit_admin_product_path(product)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2>New Product</h2>
<%= simple_form_for [:admin,@product] do |f| %>
<div class="group">
  <%= f.input :title,label:"名称" %>
</div>

<div class="group">
  <%= f.input :description,label:"描述" %>
</div>

<div class="group">
  <%= f.input :quantity,label:"数量" %>
</div>

<div class="group">
  <%= f.input :price,label:"价格" %>
</div>
<div class="group">
  <%= f.input :image, as: :file %>
</div>

<div class="group">

  <%= f.file_field :avatars, multiple: 'true' %>
</div>

<%= f.submit "确定",data: {disable_with: "提交中..."},class:"btn btn-sm btn-primary" %>
<% end %>

app/views/admin/products/show.html.erb
<h2>产品详情</h2>
名称: <%= @product.title %>
<br>
描述: <%= @product.description%>
<br>
数量: <%= @product.quantity %>
<br>
价格: <%= @product.price %>
<br>
<% if !@product.image.file.nil? %>
<span>商品图</span>
<br>
<%= image_tag(@product.image.thumb.url) %>
<% end %>

<% @product.avatars.each do |a| %>
展示图: <%= image_tag(a.thumb.url) %>
<% end %>