config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end
 resources :cart_items

 resources :orders do
   member do
     post :pay_with_alipay
     post :pay_with_wechat
     post :apply_to_cancel
   end
 end

 namespace :account do
   resources :orders
 end

root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.new
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    return sum
  end

  def clean!
    cart_items.delete_all
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :groupships
  has_many :products, :through => :groupships

end

app/models/groupship.rb
class Groupship < ApplicationRecord
  belongs_to :product
  belongs_to :group
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token
  belongs_to :user
  has_many :product_lists
  validates :billing_name, presence:{message:"请填写订购人姓名"}
  validates :billing_address,presence:{message:"请填写订购人地址"}
  validates :shipping_name,presence:{message:"请填写收件人姓名"}
  validates :shipping_address,presence:{message:"请填写收件人地址"}

  def generate_token
      self.token = SecureRandom.uuid
  end

  def set_payment_with!(method)
    self.update_columns(payment_method: method)

  end

  def pay!
    self.update_columns(is_paid: true)

  end

  include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned

    event :make_payment, after_commit: :pay! do
    transitions from: :order_placed, to: :paid
    end

    event :ship do
    transitions from: :paid, to: :shipping
    end

    event :deliver do
    transitions from: :shipping, to: :shipped
    end

    event :return_good do
    transitions from: :shipped, to: :good_returned
    end

    event :cancel_order do
    transitions from: [:order_placed, :paid], to: :order_cancelled
    end

  end

end

app/models/product.rb
class Product < ApplicationRecord
  validates :title,presence: true
  validates :price, presence: {message:"请填入商品价格"}
  validates :quantity, presence: {message:"请填入商品数量"}
  mount_uploader :image, ImageUploader
  mount_uploaders :avatars, AvatarUploader
  serialize :avatars, JSON

  has_many :cart_items

  belongs_to :category

  has_many :groupships
has_many :groups, :through => :groupships
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

   def admin?
     is_admin
   end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

 def index
   @products = current_cart.products
   @cart_items = current_cart.cart_items
 end


 def clean
   current_cart.clean!
   flash[:alert]="You have deleted cart"
   redirect_to :back
 end

 def checkout
  @order = Order.new
 end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
 before_action :authenticate_user!,only: [:create]

 def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price

    if @order.save

      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order = @order
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.quantity = cart_item.quantity
        product_list.save
      end
     current_cart.clean!
     OrderMailer.notify_order_placed(@order).deliver!

      redirect_to order_path(@order.token)
    else
      render 'carts/checkout'
    end
  end

def show
  @order = Order.find_by_token(params[:id])
  @product_lists = @order.product_lists
end

def pay_with_alipay
  @order = Order.find_by_token(params[:id])
  @order.set_payment_with!("alipay")
  @order.make_payment!
  redirect_to order_path(@order.token),notice: "使用支付宝成功完成付款"

end

def pay_with_wechat
  @order = Order.find_by_token(params[:id])
  @order.set_payment_with!("wechat")
  @order.make_payment!
  redirect_to order_path(@order.token), notice: "使用微信成功完成付款"

end

def apply_to_cancel
  @order = Order.find(params[:id])
  OrderMailer.apply_cancel(@order).deliver!
  flash[:notice] = "已提交申请"
  redirect_to :back
end

private

def order_params
  params.require(:order).permit(:billing_name,:billing_address,:shipping_name,:shipping_address)
end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def render_cart_total_price(cart)
  cart.total_price
  end
end

app/helpers/flashe_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper

  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
  end
end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashe.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Store
        <br>Design by xyy

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">水果庄园 </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          <li class="active">
         <%= link_to("商品", products_path) %>
          </li>
         </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to carts_path do %>购物车
                <i class="fa fa-shopping-cart"> </i>(<%= current_cart.products.count %>)
                <% end %>

              </li>
              <% if !user_signed_in? %>
              <li><%= link_to '注册',new_user_registration_path %></li>
              <li><%= link_to(content_tag(:i,'登入',class: 'fa fa-sign-in'),new_user_session_path) %></li>
              <% else %>
              <li class= "dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Hi!, <%= current_user.email %>
                  <b class="caret"></b>
                </a>
              <ul class="dropdown-menu">
                <% if current_user && current_user.is_admin == true %>
                <li> <%= link_to(content_tag(:i,'admin panel', class:"fa fa-user-circle-o"),admin_products_path) %></li>
                <% end %>
                <li> <%= link_to(content_tag(:i,'我的订单',class: 'fa fa-file-text-o'),account_orders_path) %></li>
                <li> <%= link_to(content_tag(:i,'登出',class: 'fa fa-sign-out'),destroy_user_session_path,method: :delete)%></li>


              </ul>
              </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JDstore 后台</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="turbolinks-cache-control" content="no-cache">
</head>
<body>
  <div class="container-fluid">

    <%= render "common/navbar" %>
  </div>
    <div class="container">
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("Products", admin_products_path) %> </li>
          <li> <%= link_to("Orders",admin_orders_path) %></li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render_page_title_tag %>
    <%= render_page_description_meta_tag %>
    <%= render_page_keywords_meta_tag %>
    <%= render_page_image_link_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Navigation -->

        <%= render "common/navbar" %>

        <%= render "common/flashes" %>
      <!-- Page Header -->
      <header class="masthead" style="background-image: url(<%=asset_path'img/fruit.jpg'%>)">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
              <div class="site-heading">
                <h1>Fruit Garden</h1>
                <span class="subheading">An Online Fruit Store </span>
              </div>
            </div>
          </div>
        </div>
      </header>

    <%= yield %>

    <!-- Footer -->
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
              <ul class="list-inline text-center">
                <li class="list-inline-item">
                  <a href="#">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
              </ul>
              <p class="copyright text-muted">Copyright &copy; Your Website 2017</p>
            </div>
          </div>
        </div>
      </footer>

  </body>
</html>